### ISSUE TITLE
Working on something similar

### ISSUE THREAD

**Issue by jvliwanag** [d86leader/purescript-undefined-or#1]
Hi! Just wanted to mention I'm working on something similar over at:

https://github.com/jvliwanag/purescript-oneof

I've even named a data type `UndefinedOr` as well. :) Been trying to use the union data type from that lib for FFI's as well. With a particular focus on autogenerating FFI code from docs/ts definitions.

**Comment by maurges** [comment]
Oh, that's a really nice library, it would have been useful to me. Did you consider publishing it on pursuit and in package sets? It's quite inconvenient to write a code where one non-package-set library depends on another non-package-set library. That's the only reason I've published mine.

And this library is a bit different from yours since it provides nice instances as well.

**Comment by jvliwanag** [comment]
Yeah, I really should publish it as a package set and on pursuit. :) Alright, will watch out for your work. Closing this.
